package ru.itmo.wp.model.repository;

import ru.itmo.wp.model.database.DatabaseUtils;
import ru.itmo.wp.model.domain.Entity;
import ru.itmo.wp.model.exception.RepositoryException;

import javax.sql.DataSource;
import java.sql.*;
import java.util.*;

public abstract class BasicRepository {
    protected final DataSource DATA_SOURCE = DatabaseUtils.getDataSource();

    protected Entity findByKey(String key, Object value) {
        return findByKeys(new HashMap<String, Object>(){{
            put(key, value);
        }});
    }

    protected Entity findByKeys(Map<String, Object> keyToValue) {
        String entityName = DatabaseUtils.getEntityName(this.getClass().getSimpleName());
        try (Connection connection = DATA_SOURCE.getConnection()) {
            String sql = DatabaseUtils.getSelectStringSQL(entityName, keyToValue.keySet());

            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                DatabaseUtils.setStatement(statement, keyToValue.values().toArray());

                try (ResultSet resultSet = statement.executeQuery()) {
                    return toEntityImpl(statement.getMetaData(), resultSet);
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't find " + entityName + ".", e);
        }
    }

    protected void saveByKeys(Entity entity, Map<String, Object> keyToValue) {
        String entityName = DatabaseUtils.getEntityName(this.getClass().getSimpleName());
        try (Connection connection = DATA_SOURCE.getConnection()) {
            String sql = DatabaseUtils.getInsertStringSQL(entityName, keyToValue.keySet());

            try (PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
                DatabaseUtils.setStatement(statement, keyToValue.values().toArray());
                if (statement.executeUpdate() != 1) {
                    throw new RepositoryException("Can't save " + entityName + ".");
                } else {
                    ResultSet generatedKeys = statement.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        entity.setId(generatedKeys.getLong(1));
                        entity.setCreationTime(findByKey("id", entity.getId()).getCreationTime());

                    } else {
                        throw new RepositoryException("Can't save " + entityName + " [no autogenerated fields].");
                    }
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't save " + entityName + ".", e);
        }
    }


    protected List<Entity> findAllEntities() {
        List<Entity> entities = new ArrayList<>();
        String entityName = DatabaseUtils.getEntityName(this.getClass().getSimpleName());

        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM " + entityName + " ORDER BY id DESC")) {
                try (ResultSet resultSet = statement.executeQuery()) {
                    Entity entity;
                    while ((entity = toEntityImpl(statement.getMetaData(), resultSet)) != null) {
                        entities.add(entity);
                    }
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't find " + entityName + ".", e);
        }
        return entities;
    }

    public int findCount() {
        String entityName = DatabaseUtils.getEntityName(this.getClass().getSimpleName());
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("SELECT COUNT(*) FROM " + entityName)) {
                try (ResultSet resultSet = statement.executeQuery()) {
                    if (resultSet.next()) {
                        return resultSet.getInt(1);
                    }
                    return 0;
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't find " + entityName + ".", e);
        }
    }

   protected abstract Entity toEntityImpl(ResultSetMetaData metaData, ResultSet resultSet) throws SQLException;
}
